# Reek configuration
# See https://github.com/troessner/reek

exclude_paths:
  - db/migrate
  - test
  - config
  - bin
  - vendor

detectors:
  # Don't require documentation comments for every class/module
  IrresponsibleModule:
    enabled: false

  # Boolean parameters are sometimes necessary in components
  BooleanParameter:
    enabled: false

  # Rails migrations use 't' as standard convention
  UncommunicativeVariableName:
    enabled: false

  # Utility functions are fine in mailer previews
  UtilityFunction:
    exclude:
      - PasswordsMailerPreview

  # Rails controllers use before_action to set instance variables
  InstanceVariableAssumption:
    enabled: false

  # Control parameters are common in styling helpers
  # ControlParameter:
  #   enabled: false

  # View components often have many configuration options
  # LongParameterList:
  #   enabled: false

  TooManyInstanceVariables:
    max_instance_variables: 12

  # Component classes often have case statements for variants
  # RepeatedConditional:
  #   enabled: false

  TooManyStatements:
    max_statements: 8

  # DuplicateMethodCall:
  #   max_calls: 5
